name: Deploy Lambda

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci --production

      - name: Zip Lambda function
        run: |
          cd src && zip -r ../deploy.zip .
          cd ..
          zip -g deploy.zip package.json
          zip -r -g deploy.zip node_modules

      - name: Deploy to AWS Lambda
        uses: appleboy/lambda-action@v0.2.0
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: eu-north-1
          function_name: ${{ github.ref == 'refs/heads/main' && 'process-contact-requests' || 'process-contact-requests' }}
          zip_file: deploy.zip
